name: BookMySeat CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t bookmyseat-backend-ci ./backend

      - name: Build frontend image
        run: docker build -t bookmyseat-frontend-ci ./frontend